class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // App Branding & Navigation
      'app_title': 'Tamkeen',
      'app_subtitle': 'Learning Adventure',
      'nav_adventure': 'Adventure',
      'nav_reading': 'Reading',
      'nav_math': 'Math Lab',
      'nav_trophies': 'Trophies',
      'nav_guardian': 'Guardian',

      // Header
      'student_name': 'Learner',
      'student_title': 'Explorer',
      'student_level': 'L1',
      'level_journey': 'Adventure Journey',
      'xp_progress': 'XP Progress',
      'daily_goals': 'Daily Goals',

      // Mascot Nour
      'mascot_name': 'Nour',
      'mascot_name_ar': '',
      'ai_companion': 'AI Companion',
      'btn_listen': 'Listen',
      'btn_stop': 'Stop',
      'mascot_speech_home': 'Awesome job! Ready to conquer the Echo Cavern story? Let\'s discover new sound crystals! 🌟',

      // Adventure Realms
      'realm_words': 'Realm of Words',
      'realm_words_sub': 'World of Words & Stories',
      'citadel_numbers': 'Citadel of Numbers',
      'citadel_numbers_sub': 'Fortress of Playful Numbers',
      'rope_bridge': 'Rope Bridge to Citadel of Numbers ⬇️',

      // Stages
      'stage_12_title': '12. Phonics Glade',
      'stage_12_sub': 'Letter Melodies & Phonics',
      'stage_13_title': '13. Syllable Springs',
      'stage_13_sub': 'Syllable Blending Springs',
      'stage_14_title': '14. Echo Cavern',
      'stage_14_sub': 'Voice Karaoke & Reading Arena',
      'stage_15_title': '15. Equation Fortress',
      'stage_15_sub': 'Handwriting & Addition Fortress',
      'stage_16_title': '16. Fraction Castle',
      'stage_16_sub': 'Visual Addition & Fractions',
      'stage_17_title': '17. Time Portal',
      'stage_17_sub': 'Speed & Balance Equations',
      'stage_18_title': '18. Master Equation',
      'stage_18_sub': 'Grand Precision Challenge 🎯',
      'drawing_target_precision': 'Target Precision',
      'btn_play_now': 'PLAY NOW!',
      'stage_locked_title': 'Stage Locked 🔒',
      'stage_locked_desc': 'Complete the previous adventure challenge to unlock this stage!',
      'btn_back_to_map': 'Back to Adventure Map',

      // Mini Challenges
      'todays_challenges': 'Today\'s Mini Challenges',
      'challenges_available': '2 Available',
      'word_harmony': 'Word Harmony',
      'word_harmony_desc': 'Match 5 rhyming words',
      'dot_counting': 'Dot Counting',
      'dot_counting_desc': 'Subitize & circle dots',
      'mystery_chest': 'Daily Mystery Chest',
      'chest_unlocks_in': 'Next free chest unlocks in: 02:45:10',
      'btn_peek': 'Peek 🔒',

      // Reading Arena (Dyslexia)
      'reading_story_title': 'The Brave Little Falcon',
      'comfort_deck': 'Dyslexia Comfort Deck',
      'focus_ruler': 'Focus Ruler',
      'spacing_18x': '1.8x Spacing',
      'opendyslexic': 'OpenDyslexic',
      'mascot_reading_instruction': 'Take your time! Read aloud as the golden light glides.',
      'reading_passage_1': 'The little falcon spread its wings and looked down from the mountain peak.',
      'reading_passage_2': 'The warm desert wind whispered encouraging secrets through the golden dunes.',
      'sound_out': 'Sound out:',
      'sound_breakdown': 'en • cour • ag • ing',
      'listening_indicator': 'Listening... Speak naturally 🎙️',
      'listen_to_nour': 'Listen to Nour read this sentence',
      'magnificent_reading': 'Magnificent Reading! ⭐⭐⭐',
      'pacing_label': 'Pacing',
      'pacing_val': '72 WPM (Steady)',
      'accuracy_label': 'Accuracy',
      'accuracy_val': '96% Super Falcon!',
      'expression_label': 'Expression',
      'expression_val': '4.8 Gentle Pauses',
      'words_mastered': 'Words Mastered: 18',
      'discovery_word': '1 Discovery Word',
      'discovery_word_title': '"encouraging"',
      'discovery_word_meaning': 'Meaning: Giving courage & hope',
      'btn_try_again': 'Try again',
      'btn_continue_quest': 'Continue Quest 🌟 +50',

      // Math Lab (Dyscalculia)
      'zen_mode': 'Zen Mode • Take your time 🌱',
      'gentle_growth': 'Gentle Growth',
      'step_progress': 'Step 3 of 5',
      'regrouping_quest': 'Regrouping Quest',
      'hide_visuals': 'Hide visual blocks',
      'tens_rods': 'Tens Rods (4 + 2 = 6 tens)',
      'ones_cubes': 'Ones Cubes (5 + 8 = 13 ones → 1 ten + 3 ones)',
      'magic_canvas': 'Magic Canvas',
      'big_keypad': 'Big Keypad',
      'cnn_vision_model': 'CNN Vision Model:',
      'cnn_status_ready': 'Ready',
      'nour_hint_title': 'Nour\'s Friendly Hint',
      'nour_hint_text': 'Step 1: Try adding the tens first: 40 + 20 = 60!',
      'need_next_clue': 'Need next clue? ⌵',
      'check_answer': 'Check Answer',
      'calm_breathing_break': 'Take a Calm Breathing Break',

      // Trophy Room & Skills
      'explorer_rank': 'Junior Wordsmith & Math Scout',
      'stars_count': '340 Stars',
      'badges_count': '12 Badges',
      'tab_skill_tree': 'Skill Tree',
      'tab_badges': 'Badges',
      'tab_activity': 'Activity',
      'knowledge_constellation': 'Knowledge Constellation',
      'dual_mastery': 'Dual Mastery',
      'fluency_scout': 'Fluency Scout',
      'phonics_hero': 'Phonics Hero',
      'word_master': 'Word Master',
      'geometry_quest': 'Geometry Quest',
      'equation_hunter': 'Equation Hunter',
      'math_wizard': 'Math Wizard',
      'core_wisdom_root': 'Core Wisdom Root',
      'status_mastered': 'Mastered ✓',
      'status_in_progress': 'In Progress',
      'status_locked': 'Unlocks Lvl 8',
      'weekly_chest_title': 'Weekly Explorer Chest!',
      'weekly_chest_sub': 'Contains +50 Stars & 1 Mystery Pin',
      'btn_open_gift': 'Open 🎁',

      // Guardian Dashboard
      'guardian_pin_active': 'PIN Active',
      'student_details': 'Age 8 • Grade 3 (Dyslexia & Math Support)',
      'this_week': 'This Week (Oct 14 - 21)',
      'btn_export_pdf': 'Export PDF',
      'cognitive_state': 'Cognitive & Emotional State',
      'calm_pacing': 'Calm Pacing',
      'realtime_telemetry': 'Real-time engagement telemetry',
      'frustration_index': 'Frustration Index',
      'frustration_val': '14% Very Low',
      'frustration_sub': '-22% since activating Zen Timer and gentle audio cues.',
      'focus_joy': 'Focus & Joy State',
      'focus_val': '88% Deep Flow',
      'focus_sub': 'Consistently high while solving visual phoneme puzzles.',
      'avg_daily_session': 'Avg Daily Session',
      'avg_daily_val': '24m Optimal',
      'avg_daily_sub': 'Safely under the 35 min cognitive exhaustion threshold.',
      'dyslexia_reading_fluency': 'Dyslexia & Reading Fluency',
      'wpm_gain': '+54% WPM',
      'wpm_chart_title': 'Words Per Minute (WPM) Progress 48 → 74 WPM',
      'acoustic_error_profiling': 'Acoustic Error Profiling',
      'substitutions': 'Substitutions',
      'hesitations': 'Hesitations',
      'omissions': 'Omissions',
      'phonetic_focus_title': 'Phonetic Focus: Consonant clusters (str-, spl-) and Arabic elongated vowels remain highest cognitive hesitation.',
      'dyscalculia_skill_tracing': 'Dyscalculia & Skill Tracing',
      'pybkt_badge': 'v3.2 AI Model',
      'pybkt_sub': 'Bayesian Knowledge Tracing (PyBKT Model)',
      'skill_addition': 'Single-digit Addition & Subtraction',
      'skill_regrouping': 'Tens Regrouping (Base-10 Spatial)',
      'skill_number_line': 'Number Line Spatial Estimation',
      'skill_equations': 'Multi-step Story Equations',
      'caregiver_insights': 'Caregiver Actionable Insights',
      'sensory_tip_title': 'Sensory Tip of the Week',
      'sensory_tip_body': 'Zaid solves regrouping problems 2.4x faster when using tactile representations before abstract numbers.',
      'tamkeen_bot_title': 'Tamkeen Owl Bot:',
      'tamkeen_bot_body': '"Zaid thrives best when sessions occur before 5:00 PM. Evening tries exhibit 30% higher hesitation pauses."',
      'accessibility_accommodations': 'Accessibility Accommodations',
      'acc_opendyslexic': 'OpenDyslexic Heavy Font',
      'acc_opendyslexic_sub': 'Weighted bottom baselines to prevent letter inversion.',
      'acc_zen': 'Zen Mode (Hide Timers)',
      'acc_zen_sub': 'Removes all ticking countdowns to eliminate anxiety.',
      'acc_audio_guidance': 'Audio-First Guidance',
      'acc_audio_guidance_sub': 'Automatic mascot narration of all question stems.',
      'font_size': 'Font Size',
      'font_size_sub': 'Adjust text scaling across the entire application',
      'font_size_standard': 'Standard Size',
      'font_size_large': 'Large Size',
      'font_size_extra_large': 'Extra Large',
      'font_size_small': 'Compact Size',
      'font_size_reset': 'Reset Size',
      'font_size_increase': 'Increase Font Size',
      'font_size_decrease': 'Decrease Font Size',

      // Guided Interactive Tour (flutter_intro)
      'tour_guide_tooltip': 'Interactive Guide Tour',
      'tour_btn_next': 'Next',
      'tour_btn_prev': 'Previous',
      'tour_btn_finish': 'Finish Tour',
      'tour_btn_skip': 'Skip Tour',
      'tour_step_counter': 'Step',
      'tour_of': 'of',
      'tour_function_title': 'How does it work?',
      'tour_symbol_title': 'What does it represent?',

      // Steps 1 to 9
      'tour_step_1_title': 'Language Switcher',
      'tour_step_1_func': 'Instantly switches between 100% Arabic and 100% English modes with full layout adaptation.',
      'tour_step_1_sym': 'Symbolizes accessibility and linguistic inclusion, tailored for every student and family.',

      'tour_step_2_title': 'Daily Streak Flame',
      'tour_step_2_func': 'Tracks consecutive days the learner completed at least one reading or math activity.',
      'tour_step_2_sym': 'Symbolizes perseverance and dedication, turning learning into a joyful daily habit.',

      'tour_step_3_title': 'Golden Stars Balance',
      'tour_step_3_func': 'Instant rewards earned by reading passages smoothly or solving equations accurately.',
      'tour_step_3_sym': 'Symbolizes encouragement and celebration of effort, used to unlock mystery chests.',

      'tour_step_4_title': 'Explorer Profile & Level',
      'tour_step_4_func': 'Displays explorer rank and level. Tap it to view cloud profile details and role.',
      'tour_step_4_sym': 'Symbolizes learner identity and personal milestone progress across quests.',

      'tour_step_5_title': 'Interactive Adventure Map',
      'tour_step_5_func': 'The primary roadmap guiding the learner through progressive stages across Words and Numbers.',
      'tour_step_5_sym': 'Symbolizes gamified discovery, turning structured curriculum into an exciting journey.',

      'tour_step_6_title': 'Reading Fluency Arena',
      'tour_step_6_func': 'Dyslexia studio with focus ruler, syllable chunking, and real-time acoustic speech evaluation.',
      'tour_step_6_sym': 'Symbolizes breaking the fear of reading aloud and building phonetic confidence.',

      'tour_step_7_title': 'Math Equation Lab',
      'tour_step_7_func': 'Dyscalculia lab featuring digit drawing recognition, base-10 blocks, and interactive number lines.',
      'tour_step_7_sym': 'Symbolizes transforming abstract math into tactile, visual, and intuitive understanding.',

      'tour_step_8_title': 'Trophies & Skill Constellation',
      'tour_step_8_func': 'Presents the knowledge constellation, skill masteries, badges, and activity history.',
      'tour_step_8_sym': 'Symbolizes celebrating mastery and honoring each learner\'s unique cognitive strengths.',

      'tour_step_9_title': 'Guardian Diagnostic Dashboard',
      'tour_step_9_func': 'PIN-protected clinical telemetry analyzing reading speed, Bayesian knowledge tracing, and focus.',
      'tour_step_9_sym': 'Symbolizes an evidence-based partnership between parents, educators, and the child.',


      // Guardian Logout
      'guardian_logout_title': 'Log Out of Account',
      'guardian_logout_sub': 'Safely sign out and return to student login screen',
      'guardian_logout_btn': 'Log Out',
      'guardian_logout_dialog_title': 'Confirm Log Out',
      'guardian_logout_dialog_desc': 'Are you sure you want to log out? All learner progress and trophies are safely synced to the cloud.',
      'guardian_logout_cancel': 'Cancel',
      'guardian_logout_confirm': 'Yes, Log Out',

      // AI Backend Server
      'guardian_server_title': 'AI Intelligence Server (ngrok)',
      'guardian_server_sub': 'FastAPI backend tunnel on port 8000 powering Dyslexia, Dyscalculia & Symbol CNN models',
      'guardian_server_url': 'Active Server URL',
      'guardian_server_test_btn': 'Test Connection',
      'guardian_server_connected': 'Connected to AI Models',
      'guardian_server_offline': 'Server Offline (Start run_server.bat)',
      'guardian_server_waiting': 'ngrok online, waiting for local server...',
      'guardian_server_edit': 'Change ngrok URL',
      'guardian_server_save': 'Save URL',
      'guardian_server_reset': 'Reset Default',
    },
    'ar': {
      // App Branding & Navigation
      'app_title': 'تمكين',
      'app_subtitle': 'مغامرة التعلم الممتعة',
      'nav_adventure': 'المغامرة',
      'nav_reading': 'حلبة القراءة',
      'nav_math': 'معمل الحساب',
      'nav_trophies': 'الجوائز',
      'nav_guardian': 'ولي الأمر',

      // Header
      'student_name': 'المتعلم',
      'student_title': 'مستكشف',
      'student_level': 'م1',
      'level_journey': 'رحلة الاستكشاف',
      'xp_progress': 'النقاط والتقدم',
      'daily_goals': 'المهام اليومية',

      // Mascot Nour
      'mascot_name': 'نور',
      'mascot_name_ar': '',
      'ai_companion': 'المرشد الذكي',
      'btn_listen': 'استمع',
      'btn_stop': 'إيقاف',
      'mascot_speech_home': 'عمل رائع يا بطل! هل أنت مستعد لخوض قصة كهف الصدى اليوم واكتشاف بلورات صوتية جديدة؟ 🌟',

      // Adventure Realms
      'realm_words': 'عالم الكلمات والقصص',
      'realm_words_sub': 'رحلة القراءة والطلاقة اللغوية',
      'citadel_numbers': 'قلعة الأرقام الممتعة',
      'citadel_numbers_sub': 'حصن العمليات الحسابية والمعادلات',
      'rope_bridge': 'جسر الحبال إلى قلعة الأرقام ⬇️',

      // Stages
      'stage_12_title': '12. واحة الأصوات',
      'stage_12_sub': 'واحة الأصوات والتهجئة',
      'stage_13_title': '13. ينابيع المقاطع',
      'stage_13_sub': 'ينابيع المقاطع والكلمات',
      'stage_14_title': '14. كهف الصدى',
      'stage_14_sub': 'حلبة القراءة التفاعلية وعسر القراءة',
      'stage_15_title': '15. حصن المعادلات',
      'stage_15_sub': 'الكتابة باليد والتعرف الذكي',
      'stage_16_title': '16. قصر الكسور',
      'stage_16_sub': 'الجمع البصري والكسور',
      'stage_17_title': '17. بوابة الزمن',
      'stage_17_sub': 'السرعة وتوازن المعادلات',
      'stage_18_title': '18. عرش العباقرة',
      'stage_18_sub': 'تحدي الدقة المتناهية 🎯',
      'drawing_target_precision': 'دقة الرسم المطلوبة',
      'btn_play_now': 'العب الآن!',
      'stage_locked_title': 'المرحلة مقفلة 🔒',
      'stage_locked_desc': 'أكمل المرحلة السابقة في خريطة المغامرة أولاً لفتح هذا التحدي!',
      'btn_back_to_map': 'العودة لخريطة المغامرة',

      // Mini Challenges
      'todays_challenges': 'تحديات اليوم السريعة',
      'challenges_available': '2 متاحة',
      'word_harmony': 'انسجام الكلمات',
      'word_harmony_desc': 'طابق 5 كلمات متناغمة القافية',
      'dot_counting': 'عد النقاط السريع',
      'dot_counting_desc': 'التقدير البصري ومجموعات النقاط',
      'mystery_chest': 'صندوق المفاجآت اليومي',
      'chest_unlocks_in': 'يتاح فتح الصندوق بعد: 02:45:10',
      'btn_peek': 'معاينة 🔒',

      // Reading Arena (Dyslexia)
      'reading_story_title': 'الصقر الصغير الشجاع',
      'comfort_deck': 'لوحة راحة القراءة والديسلكسيا',
      'focus_ruler': 'مسطرة التركيز',
      'spacing_18x': 'تباعد 1.8',
      'opendyslexic': 'خط القراءة السلس',
      'mascot_reading_instruction': 'خذ كامل وقتك! اقرأ بصوت واضح بينما يتحرك الضوء الذهبي.',
      'reading_passage_1': 'فرد الصقر الصغير جناحيه ونظر لأسفل من قمة الجبل الشاهق.',
      'reading_passage_2': 'همست رياح الصحراء الدافئة بأسرار مشجعة وملهمة عبر الكثبان الذهبية.',
      'sound_out': 'تهجئة المقطع:',
      'sound_breakdown': 'مُ • شَ • جِّ • عَ • ة',
      'listening_indicator': 'جارٍ الاستماع... تكلّم بطبيعتك 🎙️',
      'listen_to_nour': 'استمع لنور يقرأ الجملة بصوته',
      'magnificent_reading': 'قراءة رائعة ومبهرة! ⭐⭐⭐',
      'pacing_label': 'السرعة',
      'pacing_val': '72 كلمة/دقيقة (ثابت)',
      'accuracy_label': 'الدقة',
      'accuracy_val': '96% صقر خارق!',
      'expression_label': 'التعبير والنغمة',
      'expression_val': '4.8 وقفات هادئة',
      'words_mastered': 'الكلمات المتقنة: 18',
      'discovery_word': 'كلمة اكتشاف جديدة',
      'discovery_word_title': '"مشجعة"',
      'discovery_word_meaning': 'المعنى: تمنح الشجاعة والأمل',
      'btn_try_again': 'أعد المحاولة',
      'btn_continue_quest': 'تابع المهمة 🌟 +50',

      // Math Lab (Dyscalculia)
      'zen_mode': 'نمط الهدوء • خذ كامل وقتك 🌱',
      'gentle_growth': 'نمو تدريجي مريح',
      'step_progress': 'الخطوة 3 من 5',
      'regrouping_quest': 'مهمة إعادة التجميع',
      'hide_visuals': 'إخفاء المكعبات البصرية',
      'tens_rods': 'أعمدة العشرات (4 + 2 = 6 عشرات)',
      'ones_cubes': 'مكعبات الآحاد (5 + 8 = 13 آحاد → عشرة واحدة و 3 آحاد)',
      'magic_canvas': 'لوحة الرسم السحرية',
      'big_keypad': 'لوحة أزرار كبيرة',
      'cnn_vision_model': 'موديل الرؤية الذكي للرموز:',
      'cnn_status_ready': 'جاهز ومستعد',
      'nour_hint_title': 'تلميح ذكي من نور',
      'nour_hint_text': 'الخطوة 1: جرب جمع العشرات أولاً: 40 + 20 = 60!',
      'need_next_clue': 'هل تريد دليلاً تالياً؟ ⌵',
      'check_answer': 'تحقق من الإجابة',
      'calm_breathing_break': 'استراحة تنفس واسترخاء',

      // Trophy Room & Skills
      'explorer_rank': 'بطل المفردات وكشاف الرياضيات',
      'stars_count': '340 نجمة',
      'badges_count': '12 وساماً',
      'tab_skill_tree': 'شجرة المهارات',
      'tab_badges': 'الأوسمة',
      'tab_activity': 'النشاط',
      'knowledge_constellation': 'كوكبة المعرفة المزدوجة',
      'dual_mastery': 'إتقان ثنائي',
      'fluency_scout': 'كشاف الطلاقة',
      'phonics_hero': 'بطل الصوتيات',
      'word_master': 'سيد الكلمات',
      'geometry_quest': 'مهمة الهندسة',
      'equation_hunter': 'صائد المعادلات',
      'math_wizard': 'ساحر الرياضيات',
      'core_wisdom_root': 'جذر الحكمة الأساسي',
      'status_mastered': 'تم الإتقان ✓',
      'status_in_progress': 'قيد التقدم',
      'status_locked': 'يفتح في م8',
      'weekly_chest_title': 'صندوق المستكشف الأسبوعي!',
      'weekly_chest_sub': 'يحتوي على +50 نجمة ودبوس استكشاف مميز',
      'btn_open_gift': 'فتح الهدية 🎁',

      // Guardian Dashboard
      'guardian_pin_active': 'محمي برمز سري',
      'student_details': 'العمر 8 سنوات • الصف الثالث (دعم القراءة والحساب)',
      'this_week': 'هذا الأسبوع (14 - 21 أكتوبر)',
      'btn_export_pdf': 'تصدير التقرير',
      'cognitive_state': 'الحالة المعرفية والانفعالية',
      'calm_pacing': 'وتيرة هادئة',
      'realtime_telemetry': 'قياسات تفاعل الطفل في الوقت الحقيقي',
      'frustration_index': 'مؤشر الإحباط',
      'frustration_val': '14% منخفض جداً',
      'frustration_sub': 'انخفاض 22% منذ تفعيل النمط الهادئ والمساعد الصوتي.',
      'focus_joy': 'مستوى التركيز والاستمتاع',
      'focus_val': '88% تدفق ذهني ممتاز',
      'focus_sub': 'مستوى مرتفع ومستقر أثناء حل التحديات البصرية الصوتية.',
      'avg_daily_session': 'متوسط الجلسة اليومية',
      'avg_daily_val': '24 دقيقة مثالية',
      'avg_daily_sub': 'ضمن النطاق الآمن بعيداً عن الإجهاد الإدراكي (35 دقيقة).',
      'dyslexia_reading_fluency': 'الديسلكسيا والطلاقة القرائية',
      'wpm_gain': '+54% بالكلمة/دقيقة',
      'wpm_chart_title': 'تطور سرعة القراءة من 48 إلى 74 كلمة/دقيقة',
      'acoustic_error_profiling': 'تحليل الأخطاء الصوتية والنطقية',
      'substitutions': 'إبدال كلمات',
      'hesitations': 'تردد وتوقف',
      'omissions': 'تخطي كلمات',
      'phonetic_focus_title': 'التركيز الصوتي: تتابعات الحروف الساكنة وحروف المد الطويلة لا تزال نقطة التردد الأعلى.',
      'dyscalculia_skill_tracing': 'الديسكالكوليا وتتبع المهارات البايزي',
      'pybkt_badge': 'النموذج الذكي 3.2',
      'pybkt_sub': 'نموذج تتبع المعرفة البايزي المتطور',
      'skill_addition': 'الجمع والطرح للأعداد المفردة',
      'skill_regrouping': 'إعادة التجميع المكاني (نظام العشرات)',
      'skill_number_line': 'التقدير المكاني على خط الأعداد',
      'skill_equations': 'المعادلات القصصية متعددة الخطوات',
      'caregiver_insights': 'توصيات وتوجيهات عملية للمربي',
      'sensory_tip_title': 'نصيحة حسية للأسبوع',
      'sensory_tip_body': 'يحل الطالب مسائل إعادة التجميع أسرع بـ 2.4 ضعف عند استخدام مجسمات ملموسة قبل الأرقام المجردة.',
      'tamkeen_bot_title': 'مرشد تمكين الآلي:',
      'tamkeen_bot_body': '"يبدع الطالب ويصل لأفضل أداء في الجلسات قبل الساعة 5:00 مساءً؛ الجلسات المتأخرة تظهر تردد أطول بـ 30%."',
      'accessibility_accommodations': 'تسهيلات الوصول وتعديل البيئة',
      'acc_opendyslexic': 'خط ثقيل القاعدة لمنع انقلاب الحروف',
      'acc_opendyslexic_sub': 'قواعد سفلية ثقيلة للحروف لتفادي التشتت البصري.',
      'acc_zen': 'النمط الهادئ (إخفاء المؤقت التنازلي)',
      'acc_zen_sub': 'إزالة أي مؤقت زمني متحرك لمنع التوتر والضغط النفسي.',
      'acc_audio_guidance': 'الإرشاد الصوتي أولاً',
      'acc_audio_guidance_sub': 'نطق آلي لكافة رؤوس الأسئلة والتوجيهات فور ظهورها.',
      'font_size': 'حجم الخط',
      'font_size_sub': 'تعديل وتكبير حجم النصوص في جميع شاشات التطبيق',
      'font_size_standard': 'الحجم القياسي',
      'font_size_large': 'خط كبير',
      'font_size_extra_large': 'خط كبير جداً',
      'font_size_small': 'خط صغير',
      'font_size_reset': 'إعادة التعيين',
      'font_size_increase': 'تكبير حجم الخط',
      'font_size_decrease': 'تصغير حجم الخط',

      // الجولة الإرشادية التفاعلية (flutter_intro)
      'tour_guide_tooltip': 'دليل الاستخدام التفاعلي',
      'tour_btn_next': 'التالي',
      'tour_btn_prev': 'السابق',
      'tour_btn_finish': 'إنهاء الجولة',
      'tour_btn_skip': 'تخطي الجولة',
      'tour_step_counter': 'خطوة',
      'tour_of': 'من',
      'tour_function_title': 'ماذا تفعل هذه الميزة؟',
      'tour_symbol_title': 'إلى ما ترمز؟',

      // الخطوات من 1 إلى 9
      'tour_step_1_title': 'مفتاح تبديل اللغة',
      'tour_step_1_func': 'يتيح التبديل الفوري بنقرة واحدة بين الوضع العربي الكامل والوضع الإنجليزي الكامل مع تغيير اتجاه الصفحة تلقائياً.',
      'tour_step_1_sym': 'يرمز إلى الشمولية اللغوية وسهولة الوصول، لضمان تجربة تعليمية مريحة تراعي لغة المتعلم المفضلة.',

      'tour_step_2_title': 'شعلة النشاط والالتزام اليومي',
      'tour_step_2_func': 'ترصد وتوثق عدد الأيام المتتالية التي أنجز فيها الطالب تمريناً واحداً على الأقل في القراءة أو الحساب.',
      'tour_step_2_sym': 'ترمز إلى نار الشغف والمثابرة والاستمرارية، وتشجع الطفل على ترسيخ التعلم كعادة يومية محببة.',

      'tour_step_3_title': 'رصيد النجوم الذهبية',
      'tour_step_3_func': 'مكافآت تحفيزية تُمنح فورياً عند إنهاء قراءة النصوص بدقة أو رسم الأرقام وحل المعادلات الحسابية.',
      'tour_step_3_sym': 'ترمز إلى التقدير والاحتفاء الفوري بجهد الطفل، وتُستخدم لفتح صناديق الجوائز السرية ورفع رتبة المستكشف.',

      'tour_step_4_title': 'الملف الشخصي ومستوى المستكشف',
      'tour_step_4_func': 'يعرض رتبة الطالب ومستواه التعليمي الحالي، ويتيح عبر النقر عليه مراجعة تفاصيل الحساب ودور المستخدم.',
      'tour_step_4_sym': 'يرمز إلى الهوية الشخصية للمتعلم ونموه المعرفي التدريجي عبر مراحل المغامرة.',

      'tour_step_5_title': 'خريطة المغامرة التفاعلية',
      'tour_step_5_func': 'المسار التعليمي الشامل الذي ينتقل بالطفل عبر محطات ومراحل تفاعلية بين عالم الكلمات وقلعة الأرقام.',
      'tour_step_5_sym': 'ترمز إلى تحويل التعليم إلى رحلة لعب استكشافية متصلة تكسر جمود التمارين والكتب التقليدية.',

      'tour_step_6_title': 'حلبة القراءة وعسر القراءة',
      'tour_step_6_func': 'بيئة داعمة لعسر القراءة مزودة بمسطرة التركيز البصري، وتلوين المقاطع الصوتية، والتعرف الصوتي الذكي.',
      'tour_step_6_sym': 'ترمز إلى كسر حاجز الخوف من القراءة الجهرية، وبناء الطلاقة والاسترسال بأسلوب مريح ومهدئ.',

      'tour_step_7_title': 'مختبر المعادلات وعسر الحساب',
      'tour_step_7_func': 'مختبر مخصص لعسر الحساب يتيح رسم الأرقام باليد على السبورة، واستخدام المكعبات البصرية وخط الأعداد.',
      'tour_step_7_sym': 'يرمز إلى تجسيد المفاهيم الرياضية المجردة في صور حسية وحركية ملموسة يسهل على الطفل إدراكها وتخيلها.',

      'tour_step_8_title': 'صالة الأوسمة وشجرة المهارات',
      'tour_step_8_func': 'تستعرض كوكبة المعرفة الشاملة، ونسب تمكن الطفل في كل مهارة، وسجل الجلسات المنجزة، وصندوق الأسبوع.',
      'tour_step_8_sym': 'ترمز إلى تتويج النجاحات وتنمية الوعي الذاتي لدى الطالب بنقاط قوته وإنجازاته المستمرة.',

      'tour_step_9_title': 'لوحة تحكم ولي الأمر التشخيصية',
      'tour_step_9_func': 'لوحة تحليلية متقدمة محمية برمز مرور سري، توفر قياسات سريرية دقيقة لسرعة القراءة ونموذج التتبع البايزي ومؤشر التوتر.',
      'tour_step_9_sym': 'ترمز إلى الشراكة العلمية الوثيقة بين المنصة وولي الأمر لدعم تقدم الطفل ببيانات موثوقة.',


      // Guardian Logout
      'guardian_logout_title': 'تسجيل الخروج من الحساب',
      'guardian_logout_sub': 'تسجيل الخروج بأمان والعودة لشاشة تسجيل الدخول وتبديل الحساب',
      'guardian_logout_btn': 'تسجيل الخروج',
      'guardian_logout_dialog_title': 'تأكيد تسجيل الخروج',
      'guardian_logout_dialog_desc': 'هل أنت متأكد من تسجيل الخروج؟ جميع بيانات وتقدم الطالب محفوظة ومزامنة بأمان في السحابة.',
      'guardian_logout_cancel': 'إلغاء',
      'guardian_logout_confirm': 'نعم، تسجيل الخروج',

      // AI Backend Server
      'guardian_server_title': 'خادم الذكاء الاصطناعي (ngrok)',
      'guardian_server_sub': 'خادم النماذج العصبية على المنفذ 8000 لتحليل القراءة، وتتبع المهارات، والتعرف على الأرقام',
      'guardian_server_url': 'رابط السيرفر النشط',
      'guardian_server_test_btn': 'فحص الاتصال',
      'guardian_server_connected': 'متصل بنجاح بنماذج الذكاء الاصطناعي',
      'guardian_server_offline': 'السيرفر غير متصل (يرجى تشغيل run_server.bat)',
      'guardian_server_waiting': 'نفق ngrok متصل، بانتظار تشغيل السيرفر المحلي...',
      'guardian_server_edit': 'تغيير رابط ngrok',
      'guardian_server_save': 'حفظ الرابط',
      'guardian_server_reset': 'استعادة الافتراضي',
    },
  };

  static String get(String key, String langCode) {
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
